def get_dependencies():
    return [ 'alsa-lib', 'alsa-utils', 'avahi-tools', 'binutils', 'cpp',
        'flac-libs', 'gcc', 'git', 'glibc-devel', 'glibc-headers', 'gpm-libs',
        'gsm', 'keyutils-libs-devel', 'krb5-devel', 'libICE', 'libSM',
        'libX11', 'libX11-common', 'libXau', 'libXext', 'libXi', 'libXtst',
        'libao', 'libao-devel', 'libasan', 'libasyncns', 'libatomic',
        'libcom_err-devel', 'libgnome-keyring', 'libgomp', 'libmpc', 'libogg',
        'libsamplerate', 'libselinux-devel', 'libsepol-devel', 'libsndfile',
        'libubsan', 'libverto-devel', 'libvorbis', 'libxcb', 'mailcap',
        'mpfr', 'openssl-devel', 'pcre-devel', 'perl', 'perl-Business-ISBN',
        'perl-Business-ISBN-Data', 'perl-Carp', 'perl-Compress-Raw-Bzip2',
        'perl-Compress-Raw-Zlib', 'perl-Crypt-OpenSSL-Bignum',
        'perl-Crypt-OpenSSL-RSA', 'perl-Crypt-OpenSSL-Random',
        'perl-Data-Dumper', 'perl-Digest', 'perl-Digest-HMAC',
        'perl-Digest-MD5', 'perl-Digest-SHA', 'perl-Encode',
        'perl-Encode-Locale', 'perl-Error', 'perl-Exporter',
        'perl-File-Listing', 'perl-File-Path', 'perl-File-Temp',
        'perl-Filter', 'perl-Getopt-Long', 'perl-Git', 'perl-HTML-Parser',
        'perl-HTML-Tagset', 'perl-HTTP-Cookies', 'perl-HTTP-Date',
        'perl-HTTP-Message', 'perl-HTTP-Negotiate', 'perl-HTTP-Tiny',
        'perl-IO-Compress', 'perl-IO-HTML', 'perl-IO-Socket-INET6',
        'perl-IO-Socket-IP', 'perl-IO-Socket-SSL', 'perl-LWP-MediaTypes',
        'perl-Module-CoreList', 'perl-NTLM', 'perl-Net-HTTP',
        'perl-Net-SSLeay', 'perl-PathTools', 'perl-Pod-Escapes',
        'perl-Pod-Perldoc', 'perl-Pod-Simple', 'perl-Pod-Usage',
        'perl-Scalar-List-Utils', 'perl-Socket', 'perl-Socket6',
        'perl-Storable', 'perl-Term-ANSIColor', 'perl-TermReadKey',
        'perl-Text-ParseWords', 'perl-Time-HiRes', 'perl-Time-Local',
        'perl-TimeDate', 'perl-URI', 'perl-WWW-RobotRules', 'perl-constant',
        'perl-libs', 'perl-libwww-perl', 'perl-macros', 'perl-parent',
        'perl-podlators', 'perl-threads', 'perl-threads-shared',
        'perl-version', 'pulseaudio-libs', 'strace', 'vim-common',
        'vim-enhanced', 'vim-filesystem', 'which', 'zlib-devel' ]
